### ISSUE TITLE
Storageclass credentials with statefulset ?

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/blobfuse-csi-driver#128]
How can I pass azure storage account credentials for storageclass if I want to use statefulset and volumeClaimTemplates ? ( https://github.com/kubernetes-sigs/blobfuse-csi- driver/blob/master/deploy/example/statefulset.yaml )
Thanks

Is `/etc/kubernetes/azure.json` file only way? 

EDIT:
Solved with:
```
az role assignment create --assignee $(az aks show -g myRG -n myAKS --query servicePrincipalProfile.clientId -o tsv) --role "Storage Account Contributor" --scope mySA
```
and 
```
kubectl.exe rollout restart daemonset csi-blobfuse-node -n kube-system
kubectl.exe rollout restart deployment csi-blobfuse-controller -n kube-system
```

^ not sure if its needed to restart both.

**Comment by andyzhangx** [comment]
use `/etc/kubernetes/azure.json` is the only way now: https://github.com/kubernetes-sigs/blobfuse-csi-driver#prerequisite, and we are going to [support read cloud config from secret](https://github.com/kubernetes-sigs/blobfuse-csi-driver/issues/130)

**Comment by andyzhangx** [comment]
BTW, you are using statefulset which depends on dynamic provisioning, so provide service principal is the only way now, and if you are using static provisioning, you could provide your storage account by k8s secret, follow guide here: https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-provide-storage-account-name-and-keyor-sastoken
