### ISSUE TITLE
update base image with debian-base

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blobfuse-csi-driver#152]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

update base image with debian-base which has less security vulnerability:
could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/273

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
could you fix this issue? @Sakuralbj thanks

**Comment by Sakuralbj** [comment]
Ok.I'll do it
