### ISSUE TITLE
Switch glide to go modules for dependency management

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blobfuse-csi-driver#20]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes/cloud-provider-azure/pull/142

**Describe alternatives you've considered**

**Additional context**

**Comment by lizebang** [comment]
@andyzhangx I would like to work on this.

**Comment by andyzhangx** [comment]
/assign @lizebang 
there is already a PR for azure file: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/54, you could work on that when merged.
