### ISSUE TITLE
secret value should not be exposed in logs

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blobfuse-csi-driver#31]
**What happened**:
Currently secret value would be exposed in logs, while it should not

```
I0421 02:40:19.501807       1 utils.go:112] GRPC response: capabilities:<rpc:<> >
I0421 02:40:19.506657       1 utils.go:106] GRPC call: /csi.v1.Node/NodePublishVolume
I0421 02:40:19.506674       1 utils.go:107] GRPC request: volume_id:"arbitrary-volumeid" target_path:"/var/lib/kubelet/pods/cc9552fd-63de-11e9-8b22-000d3a004ffb/volumes/kubernetes.io~csi/pv-blobfuse/mount" volume_capability:<mount:<> access_mode:<mode:MULTI_NODE_MULTI_WRITER > > secrets:<key:"accountkey" value:"xxx" > secrets:<key:"accountname" value:"andyacidiag" > volume_context:<key:"containerName" value:"test" > volume_context:<key:"resourceGroup" value:"andy-aci" > volume_context:<key:"storageAccount" value:"andyacidiag" >
```

We could disable this logging easily, while I would like to filter out only the `secret` value, for the other request info, it's useful for debugging:
https://github.com/csi-driver/blobfuse-csi-driver/blob/e7b3a4c2dc4f54a3d033ec55dc282613f856225f/pkg/csi-common/utils.go#L107

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
need to port PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/64

**Comment by ZeroMagic** [comment]
The commit https://github.com/kubernetes-sigs/blobfuse-csi-driver/commit/cda78e7a95c8573fd02b42a75036f34734bd5a33 has fixed the issue.
